# Generated by Django 3.1.7 on 2021-03-30 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.PositiveIntegerField()),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('estatura', models.PositiveIntegerField()),
                ('estado_civil', models.CharField(max_length=45)),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.tipo_doc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='UniamigaApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.PositiveIntegerField()),
                ('telefono', models.PositiveIntegerField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.especialista')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.tipo_doc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='historia_clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incapacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_consulta', models.TextField(max_length=150)),
                ('enfermedades_actual', models.CharField(max_length=150)),
                ('antecedentes', models.CharField(max_length=150)),
                ('analisis', models.CharField(max_length=150)),
                ('plan_manejo', models.CharField(max_length=150)),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.pacientes')),
            ],
            options={
                'verbose_name': 'Historial clinico',
                'verbose_name_plural': 'Historias clinicas',
            },
        ),
        migrations.CreateModel(
            name='grupo_familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_titular', models.IntegerField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.pacientes')),
            ],
            options={
                'verbose_name': 'Grupo de familia',
                'verbose_name_plural': 'Grupos de familias',
            },
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.medico')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniamigaApp.pacientes')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
