# Generated by Django 3.1.7 on 2021-04-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='citas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especialista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historia_clinica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={},
        ),
        migrations.RemoveField(
            model_name='medico',
            name='numero_doc',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='tipo_doc',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='num_doc',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='tipo_doc',
        ),
        migrations.DeleteModel(
            name='grupo_familiar',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='tipo_doc',
        ),
    ]
