# Generated by Django 3.1.7 on 2021-04-03 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniamigaApp', '0003_remove_medico_especialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('estatura', models.PositiveIntegerField()),
                ('estado_civil', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='historia_clinica',
            name='pacientes',
        ),
        migrations.DeleteModel(
            name='medico',
        ),
        migrations.DeleteModel(
            name='pacientes',
        ),
    ]
