# Generated by Django 3.1.7 on 2021-04-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0004_auto_20210402_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='estatura',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='peso',
        ),
    ]
