# Generated by Django 3.1.7 on 2021-04-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0008_auto_20210404_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='user',
        ),
    ]
