# Generated by Django 3.1.7 on 2021-04-05 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniamigaApp', '0009_remove_cursos_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cursos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Inscripcion', to='UniamigaApp.cursos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Inscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='citas',
        ),
    ]
