# Generated by Django 3.1.7 on 2021-05-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0010_auto_20210404_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Media', models.FileField(blank=True, null=True, upload_to='myfolder/')),
            ],
        ),
    ]
