# Generated by Django 3.1.7 on 2021-05-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0011_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
