# Generated by Django 3.1.7 on 2021-05-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0012_delete_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Media', models.FileField(blank=True, null=True, upload_to='myfolder/')),
                ('Curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cursos', to='UniamigaApp.cursos')),
            ],
        ),
    ]
