# Generated by Django 3.1.7 on 2021-05-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0013_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cursos', to='UniamigaApp.cursos'),
        ),
    ]
