# Generated by Django 3.1.7 on 2021-05-12 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniamigaApp', '0014_auto_20210512_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='Cursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inscripcion', to='UniamigaApp.cursos'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
