# Generated by Django 3.1.7 on 2021-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0015_auto_20210512_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='Descripcion',
            field=models.TextField(max_length=150),
        ),
    ]
