# Generated by Django 3.1.7 on 2021-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniamigaApp', '0016_auto_20210512_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
